In [1]:
import torch

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = device, requires_grad = True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [4]:
my_tensor.shape

torch.Size([2, 3])

In [5]:
x = torch.empty(size = (3,3))

In [6]:
x = torch.rand(size = (3,3))
x

tensor([[0.1174, 0.1607, 0.6788],
        [0.4455, 0.1208, 0.4195],
        [0.9752, 0.3740, 0.4700]])

In [7]:
x = torch.eye(5,5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [8]:
torch.linspace(0.1,1,10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [9]:
torch.__version__

'2.9.1+cpu'

In [10]:
import numpy as np

In [11]:
lst = [3,4,5,6]
arr = np.array(lst)

In [12]:
arr.dtype

dtype('int64')

In [13]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [14]:
tensors[:2]

tensor([3, 4])

In [15]:
tensors[1:4]

tensor([4, 5, 6])

In [16]:
tensors[3] = 100
tensors

tensor([  3,   4,   5, 100])

In [17]:
arr

array([  3,   4,   5, 100])

In [18]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [19]:
tensor_arr[3] = 120
tensor_arr, arr

(tensor([  3,   4,   5, 120]), array([  3,   4,   5, 100]))

In [20]:
torch.zeros(2,3,dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.tensor(np.arange(0,15).reshape(5,3))

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [22]:
a = torch.tensor([3,4,5], dtype = torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)

In [23]:
a+b

tensor([ 7.,  9., 11.])

In [24]:
a.mul(b)

tensor([12., 20., 30.])

In [25]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [26]:
c = torch.zeros(3)

In [27]:
torch.add(a,b, out = c)

tensor([ 7.,  9., 11.])

In [28]:
c

tensor([ 7.,  9., 11.])

In [29]:
torch.add(a,b).sum()

tensor(27.)

In [30]:
a.dot(b)

tensor(62.)

In [31]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype = torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype = torch.float)

In [32]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [33]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [34]:
x@y

tensor([[55., 53.],
        [90., 92.]])